### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by moritzploss-k** [jhaals/yopass#1276]
Hi!

Thanks for this great project!

I was trying to find documentation on how to interact with the Yopass API, in particular how to POST a secret to the API. I have seen various threads and code snippets, played around with the `sjcl` JavaScript library and the `openpgp` Golang library, and read through some of the unit tests in the project.

However, since my project is written in Erlang, I don't have access to any of these libraries, and it would be very useful to have some official documentation on what the request body should look like, how secrets etc. should be formatted, and what parameters and encryption methods are supported.

I have some existing (but apparently broken) legacy code where the request body looks like this**, but I guess this is no longer supported (the POST request succeeds, but I get an error `Invalid password, please try again` when I try to decrypt the message later):

```json
{
  "secret": {
    "iv": "LxJLuerJ2rFx4oaoqmoGhg==",
    "v": 1,
    "iter": 1000,
    "ks": 128,
    "ts": 64,
    "mode": "gcm",
    "adata": "",
    "cipher": "aes",
    "salt": "/oHBzMKIBWQ=",
    "ct": "JgpKajgUSMVAF7o="
  },
  "expiration": 3600
}
```

Any help with this would be much appreciated! 🙂

** In my legacy implementation, the value associated with the `secret` key is actually a JSON string, so double-encoded as JSON, but I thought it's easier to read in the above format.

**Comment by jhaals** [comment]
Hi,

The actual rest API is dead simple, you POST json to `/secret` containing `message`, `expiration` and `one_time`. 
You can inspect the request in the browser to see the it in detail. If you're somewhat faimilar with Go this is the type https://github.com/jhaals/yopass/blob/913120c268b644f0dd6286b43c9330702398ab97/pkg/yopass/yopass.go#L42 and request https://github.com/jhaals/yopass/blob/master/pkg/yopass/client.go#L51

No encryption is done in the backend so you could in theory send any kind of payload in `message` but the frontend only knows how to decrypt openpgp. There are openpgp libraries for several languages, see https://www.openpgp.org/software/developer/ for info. 

SJCL is no longer supported since that library has very little third party usage and support.

I hope it helps, good luck!

**Comment by moritzploss-k** [comment]
thanks, that's good to know!

**Comment by Ash258** [comment]
For everyone else who will receive 404 on `POST /secret`. The API endpoint was changed to `/create/secret` in 56a1048
